/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Register addresses for STM32F103, straight from the reference manual */
#define RCC_APB2ENR   (*(volatile uint32_t *)0x40021018)
#define GPIOC_CRH     (*(volatile uint32_t *)0x40011004)
#define GPIOC_ODR     (*(volatile uint32_t *)0x4001100C)

int main(void)
{
    /* 1. Enable clock to GPIO Port C (bit 4 of RCC_APB2ENR) */
    RCC_APB2ENR |= (1 << 4);

    /* 2. Set PC13 as output push-pull, 2 MHz.
       PC13 config lives in bits 20-23 of CRH. 0b0010 = output/2MHz/push-pull */
    GPIOC_CRH &= ~(0xF << 20);
    GPIOC_CRH |=  (0x2 << 20);

    /* 3. Blink forever */
    while (1)
    {
        GPIOC_ODR ^= (1 << 13);                      /* toggle PC13 */
        for (volatile int i = 0; i < 50000; i++);   /* crude delay */
    }
}
